apiVersion: apps/v1
kind: Deployment
metadata:
  name: camunda
spec:
  selector:
    matchLabels:
      name: camunda
  template:
    metadata:
      labels:
        name: camunda
    spec:
      containers:
        - name: app
          image: camunda/camunda-bpm-platform@sha256:9ca5363c41a0a4f3730b62c4e5bdf347fe6d52af70f2c6253aeb75efc6279266
          ports:
            - containerPort: 8080